### ISSUE TITLE
About xresouces file

### ISSUE THREAD

**Issue by Vv1ct0r** [ivyl/i3-config#3]
Default font didn't works good in my laptop, so I've changed xresouces file. Problem is it works for urxvt, not for st.

**Comment by ivyl** [comment]
You sent font for st compile time. It does not read any configuration files on start. You can override the font using `-f` command line argument though. You can check my st repository for the configured version I use :-)

Terminus is handled differently on different distributions - it's "Terminus" for Fedora and "xos4 Terminus" for Arch.
