### ISSUE TITLE
Change terminal

### ISSUE THREAD

**Issue by vincentlarkin** [ivyl/i3-config#4]
Hello, I really like your config. After applying it I find the terminal is a little off. I do not personally like it. I was wondering how I could change it back to the default terminal when I do the hotkey to open the terminal? I even reset my config file and this did not fix it. Thanks
(picture included)
![2017-07-18-165613_1600x900_scrot](https://user-images.githubusercontent.com/17298607/28341588-084cf84c-6bda-11e7-9935-2a72659040ab.png)

**Comment by ivyl** [comment]
I use st (see the mod+enter binding) and what you have depicted here looks like xterm/rxvt. You have to set xresources for yourself if you want it to look nice.

The original st: http://git.suckless.org/st/

My configured "fork": https://github.com/ivyl/st/
